package com.xgn.model;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class BeginSession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.session_id
     *
     * @mbg.generated
     */
    private Long sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.device
     *
     * @mbg.generated
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.os_version
     *
     * @mbg.generated
     */
    private String osVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.locale
     *
     * @mbg.generated
     */
    private String locale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.density
     *
     * @mbg.generated
     */
    private String density;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.resolution
     *
     * @mbg.generated
     */
    private String resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column begin_session.os
     *
     * @mbg.generated
     */
    private String os;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    public BeginSession(Long sessionId, String device, String osVersion, String locale, String density, String appVersion, String resolution, String os) {
        this.sessionId = sessionId;
        this.device = device;
        this.osVersion = osVersion;
        this.locale = locale;
        this.density = density;
        this.appVersion = appVersion;
        this.resolution = resolution;
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.session_id
     *
     * @return the value of begin_session.session_id
     *
     * @mbg.generated
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.device
     *
     * @return the value of begin_session.device
     *
     * @mbg.generated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.os_version
     *
     * @return the value of begin_session.os_version
     *
     * @mbg.generated
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.locale
     *
     * @return the value of begin_session.locale
     *
     * @mbg.generated
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.density
     *
     * @return the value of begin_session.density
     *
     * @mbg.generated
     */
    public String getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.app_version
     *
     * @return the value of begin_session.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.resolution
     *
     * @return the value of begin_session.resolution
     *
     * @mbg.generated
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column begin_session.os
     *
     * @return the value of begin_session.os
     *
     * @mbg.generated
     */
    public String getOs() {
        return os;
    }
}