package com.xgn.model;

import lombok.Builder;
import lombok.Data;

import java.util.Date;

@Data
@Builder
public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_id
     *
     * @mbg.generated
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.session_id
     *
     * @mbg.generated
     */
    private Long sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.sum
     *
     * @mbg.generated
     */
    private Long sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.count
     *
     * @mbg.generated
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.dur
     *
     * @mbg.generated
     */
    private Long dur;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated
     */
    public Event(Long eventId, Long sessionId, Long sum, Long count, String key, Date timestamp, Long dur) {
        this.eventId = eventId;
        this.sessionId = sessionId;
        this.sum = sum;
        this.count = count;
        this.key = key;
        this.timestamp = timestamp;
        this.dur = dur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_id
     *
     * @return the value of event.event_id
     *
     * @mbg.generated
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.session_id
     *
     * @return the value of event.session_id
     *
     * @mbg.generated
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.sum
     *
     * @return the value of event.sum
     *
     * @mbg.generated
     */
    public Long getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.count
     *
     * @return the value of event.count
     *
     * @mbg.generated
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.key
     *
     * @return the value of event.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.timestamp
     *
     * @return the value of event.timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.dur
     *
     * @return the value of event.dur
     *
     * @mbg.generated
     */
    public Long getDur() {
        return dur;
    }
}