package com.xgn.model;

public class HttpLinkEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.even_id
     *
     * @mbg.generated
     */
    private Long evenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.hdt
     *
     * @mbg.generated
     */
    private String hdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.mt
     *
     * @mbg.generated
     */
    private String mt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.cl
     *
     * @mbg.generated
     */
    private String cl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.hc
     *
     * @mbg.generated
     */
    private String hc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.nt
     *
     * @mbg.generated
     */
    private String nt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.ru
     *
     * @mbg.generated
     */
    private String ru;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.dns
     *
     * @mbg.generated
     */
    private Long dns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.tcp
     *
     * @mbg.generated
     */
    private Long tcp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.ssl
     *
     * @mbg.generated
     */
    private Long ssl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.first_packet
     *
     * @mbg.generated
     */
    private Long firstPacket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.response
     *
     * @mbg.generated
     */
    private Long response;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_link_event.da
     *
     * @mbg.generated
     */
    private String da;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    public HttpLinkEvent(Long evenId, String hdt, String mt, String cl, String hc, String nt, String ru, Long dns, Long tcp, Long ssl, Long firstPacket, Long response, String da) {
        this.evenId = evenId;
        this.hdt = hdt;
        this.mt = mt;
        this.cl = cl;
        this.hc = hc;
        this.nt = nt;
        this.ru = ru;
        this.dns = dns;
        this.tcp = tcp;
        this.ssl = ssl;
        this.firstPacket = firstPacket;
        this.response = response;
        this.da = da;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.even_id
     *
     * @return the value of http_link_event.even_id
     *
     * @mbg.generated
     */
    public Long getEvenId() {
        return evenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.hdt
     *
     * @return the value of http_link_event.hdt
     *
     * @mbg.generated
     */
    public String getHdt() {
        return hdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.mt
     *
     * @return the value of http_link_event.mt
     *
     * @mbg.generated
     */
    public String getMt() {
        return mt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.cl
     *
     * @return the value of http_link_event.cl
     *
     * @mbg.generated
     */
    public String getCl() {
        return cl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.hc
     *
     * @return the value of http_link_event.hc
     *
     * @mbg.generated
     */
    public String getHc() {
        return hc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.nt
     *
     * @return the value of http_link_event.nt
     *
     * @mbg.generated
     */
    public String getNt() {
        return nt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.ru
     *
     * @return the value of http_link_event.ru
     *
     * @mbg.generated
     */
    public String getRu() {
        return ru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.dns
     *
     * @return the value of http_link_event.dns
     *
     * @mbg.generated
     */
    public Long getDns() {
        return dns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.tcp
     *
     * @return the value of http_link_event.tcp
     *
     * @mbg.generated
     */
    public Long getTcp() {
        return tcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.ssl
     *
     * @return the value of http_link_event.ssl
     *
     * @mbg.generated
     */
    public Long getSsl() {
        return ssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.first_packet
     *
     * @return the value of http_link_event.first_packet
     *
     * @mbg.generated
     */
    public Long getFirstPacket() {
        return firstPacket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.response
     *
     * @return the value of http_link_event.response
     *
     * @mbg.generated
     */
    public Long getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_link_event.da
     *
     * @return the value of http_link_event.da
     *
     * @mbg.generated
     */
    public String getDa() {
        return da;
    }
}