package com.xgn.mapper;

import com.xgn.model.BeginSession;

public interface BeginSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    int insert(BeginSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    int insertSelective(BeginSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    BeginSession selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BeginSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table begin_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BeginSession record);


    int save(BeginSession record);
}