package com.xgn.mapper;

import com.xgn.model.DeviceInfo;
import lombok.Builder;
import lombok.Data;
import org.apache.ibatis.annotations.Mapper;



@Mapper
public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    DeviceInfo selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceInfo record);
}