package com.xgn.mapper;

import com.xgn.model.DurationSession;

public interface DurationSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    int insert(DurationSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    int insertSelective(DurationSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    DurationSession selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DurationSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duration_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DurationSession record);

    int save(DurationSession session);
}