package com.xgn.mapper;

import com.xgn.model.EndSession;

public interface EndSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    int insert(EndSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    int insertSelective(EndSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    EndSession selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EndSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EndSession record);
}