package com.xgn.mapper;

import com.xgn.model.HttpLinkEvent;

public interface HttpLinkEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long evenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int insert(HttpLinkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int insertSelective(HttpLinkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    HttpLinkEvent selectByPrimaryKey(Long evenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HttpLinkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HttpLinkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_link_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HttpLinkEvent record);
}